services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: noisy
      POSTGRES_PASSWORD: buffer
      POSTGRES_DB: noisybuffer
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U noisy -d noisybuffer"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://noisy:buffer@db:5432/noisybuffer?sslmode=disable
      WEB_DIR: /app/web
    volumes:
      - ./cmd/noisybufferd/web:/app/web
    ports:
      - "1234:1234"
    restart: unless-stopped

volumes:
  db-data:

